/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    categories: Category;
    projects: Project;
    services: Service;
    posts: Post;
    redirects: Redirect;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    breakpoints: Breakpoint;
    social: Social;
    footer: Footer;
    header: Header;
  };
  globalsSelect: {
    breakpoints: BreakpointsSelect<false> | BreakpointsSelect<true>;
    social: SocialSelect<false> | SocialSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: HeroBlockProps;
  layout: (
    | DividerBlockProps
    | SectionBlockProps
    | SectionGroupBlockProps
    | ArchiveBlockProps
    | TabbedContentBlockProps
    | CTABlockProps
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  slug: string;
  slugLock?: boolean | null;
  url?: string | null;
  thumbnail?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlockProps".
 */
export interface HeroBlockProps {
  richText: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  heroStyle?: ('default' | 'lowImpact') | null;
  type: 'medium' | 'large';
  blurredBackground: 'true' | 'false';
  image?: (string | null) | Media;
  showBreadcrumb?: ('true' | 'false') | null;
  breadcrumbContainer?: ('none' | 'boxed') | null;
  breadcrumbBackground?: ('none' | 'light' | 'dark' | 'translucent') | null;
  breadcrumbs?:
    | {
        relationTo: {
          relationTo: 'pages';
          value: string | Page;
        };
        label: string;
        id?: string | null;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DividerBlockProps".
 */
export interface DividerBlockProps {
  type?: ('content' | 'section') | null;
  weight?: ('minimal' | 'thin' | 'thick') | null;
  width?: ('full' | 'default' | 'half') | null;
  centered?: boolean | null;
  color?: ('primary' | 'secondary' | 'accent' | 'light-grey') | null;
  opacity?: number | null;
  className?: string | null;
  /**
   * Grid appearance options for the block, this will only affect desktop screens as mobile is a standard flex one column layout.
   */
  gridAppearance?: {
    blockSize?:
      | (
          | 'col-span-1'
          | 'col-span-2'
          | 'col-span-3'
          | 'col-span-4'
          | 'col-span-5'
          | 'col-span-6'
          | 'col-span-7'
          | 'col-span-8'
          | 'col-span-9'
          | 'col-span-10'
          | 'col-span-11'
          | 'col-span-12'
          | 'col-span-13'
          | 'col-span-14'
          | 'col-span-15'
          | 'col-span-16'
        )
      | null;
    alignSelf?: ('stretch' | 'start' | 'center' | 'end') | null;
    justifySelf?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'divider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionBlockProps".
 */
export interface SectionBlockProps {
  sectionBlocks?:
    | (
        | DividerBlockProps
        | LinksBlockProps
        | LinksGroupBlockProps
        | IntroBlockProps
        | MediaBlockProps
        | CardBlockProps
        | AccordionBlockProps
        | CarouselBlockProps
        | BioBlockProps
        | ToolsBlockProps
        | TopTracksBlockProps
        | RelatedProjectsBlockProps
      )[]
    | null;
  boxedContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  appearance?: {
    /**
     * The layout of the section, you can choose between a blocks layout, boxed content, or full-width blocks layout.
     */
    sectionType?: ('default' | 'full-width' | 'boxed') | null;
    alignContent?: ('left' | 'right') | null;
    backgroundColour?:
      | (
          | 'none'
          | 'primary'
          | 'secondary'
          | 'accent'
          | 'gradient-light'
          | 'gradient-primary'
          | 'gradient-secondary'
          | 'gradient-accent'
          | 'gradient-grey'
        )
      | null;
    borderRadius?: ('none' | 'small' | 'medium' | 'large' | 'circle') | null;
  };
  blockName?: string | null;
  hiddenSlug?: string | null;
  id?: string | null;
  blockType: 'section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinksBlockProps".
 */
export interface LinksBlockProps {
  link: {
    type: 'reference' | 'custom';
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'projects';
          value: string | Project;
        } | null)
      | ({
          relationTo: 'services';
          value: string | Service;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'categories';
          value: string | Category;
        } | null);
    url?: string | null;
    label: string;
    variant?: ('fill' | 'outlined') | null;
    color?: ('primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet') | null;
    hoverColor?:
      | ('default' | 'primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet')
      | null;
    buttonShadow?: ('none' | 'small' | 'medium' | 'large') | null;
    className?: string | null;
  };
  /**
   * Grid appearance options for the block, this will only affect desktop screens as mobile is a standard flex one column layout.
   */
  gridAppearance?: {
    blockSize?:
      | (
          | 'col-span-1'
          | 'col-span-2'
          | 'col-span-3'
          | 'col-span-4'
          | 'col-span-5'
          | 'col-span-6'
          | 'col-span-7'
          | 'col-span-8'
          | 'col-span-9'
          | 'col-span-10'
          | 'col-span-11'
          | 'col-span-12'
          | 'col-span-13'
          | 'col-span-14'
          | 'col-span-15'
          | 'col-span-16'
        )
      | null;
    alignSelf?: ('stretch' | 'start' | 'center' | 'end') | null;
    justifySelf?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'links';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  hero: {
    /**
     * Use this if you want to override the project title that appears in the hero.
     */
    titleOverride: string;
    'clonedLock-110371416'?: boolean | null;
    /**
     * Use this if you want to override the project type that appears above the title.
     */
    typeOverride: string;
    'clonedLock-1380773734'?: boolean | null;
    backgroundImage?: (string | null) | Media;
    blurredBackground?: ('true' | 'false') | null;
    breadcrumbs?: {
      showBreadcrumb?: ('true' | 'false') | null;
      breadcrumbContainer?: ('none' | 'boxed') | null;
      breadcrumbBackground?: ('none' | 'light' | 'dark' | 'translucent') | null;
      breadcrumbs?:
        | {
            relationTo:
              | {
                  relationTo: 'pages';
                  value: string | Page;
                }
              | {
                  relationTo: 'projects';
                  value: string | Project;
                }
              | {
                  relationTo: 'services';
                  value: string | Service;
                };
            label: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  /**
   * The details of the project. These details will appear on the project page.
   */
  details?: {
    date?: string | null;
    type?: string | null;
    tools?: string | null;
    name?: string | null;
    url?: string | null;
    previewLabel?: string | null;
    previewUrl?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  gallery?:
    | {
        media: string | Media;
        showCaption?: boolean | null;
        caption?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Customize the appearance and behavior of the carousel. The carousel will automatically adjust to the number of items provided.
   */
  galleryOptions: {
    autoHeight: boolean;
    autoPlay: boolean;
    keyboardControls: boolean;
    buttonNavigation: boolean;
    pagination: boolean;
    loop: boolean;
    direction: 'horizontal' | 'vertical';
    focus?: boolean | null;
    paginationType?: ('bullets' | 'progress') | null;
    paginationColor?:
      | (
          | 'primary'
          | 'accent'
          | 'secondary'
          | 'urban-steel'
          | 'slate'
          | 'bitter-sweet'
          | 'cherry-punch'
          | 'fresh-leaf'
        )
      | null;
    /**
     * The spacing between slides in pixels.
     */
    slideSpacing: number;
    /**
     * The number of slides to show at a time.
     */
    slidesPerView: number;
    /**
     * The number of slides to scroll at a time.
     */
    slidesToScroll: 'auto' | '1' | '2' | '3' | '4';
  };
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The content to display in the CTA.
   */
  ctaContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The link to display in the CTA.
   */
  ctaLink: {
    type: 'reference' | 'custom';
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'projects';
          value: string | Project;
        } | null)
      | ({
          relationTo: 'services';
          value: string | Service;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'categories';
          value: string | Category;
        } | null);
    url?: string | null;
    label: string;
    variant?: ('fill' | 'outlined') | null;
    color?: ('primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet') | null;
    hoverColor?:
      | ('default' | 'primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet')
      | null;
    buttonShadow?: ('none' | 'small' | 'medium' | 'large') | null;
    className?: string | null;
  };
  /**
   * Customize the appearance of the CTA.
   */
  ctaAppearance?: {
    blockVariant?: ('fill' | 'outlined' | 'outlined-thick') | null;
    backgroundColour?:
      | (
          | 'none'
          | 'primary'
          | 'secondary'
          | 'accent'
          | 'gradient-light'
          | 'gradient-primary'
          | 'gradient-secondary'
          | 'gradient-accent'
          | 'gradient-grey'
        )
      | null;
    borderRadius?: ('none' | 'small' | 'medium' | 'large' | 'circle') | null;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  slug: string;
  slugLock?: boolean | null;
  url?: string | null;
  thumbnail?: (string | null) | Media;
  categories: (string | Category)[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  hero: {
    /**
     * Use this if you want to override the project type that appears above the title.
     */
    typeOverride: string;
    'clonedLock-1050015322'?: boolean | null;
    /**
     * Use this if you want to override the service title that appears in the hero.
     */
    titleOverride: string;
    'clonedLock-110371416'?: boolean | null;
    backgroundImage?: (string | null) | Media;
    blurredBackground?: ('true' | 'false') | null;
    breadcrumbs?: {
      showBreadcrumb?: ('true' | 'false') | null;
      breadcrumbContainer?: ('none' | 'boxed') | null;
      breadcrumbBackground?: ('none' | 'light' | 'dark' | 'translucent') | null;
      breadcrumbs?:
        | {
            relationTo:
              | {
                  relationTo: 'pages';
                  value: string | Page;
                }
              | {
                  relationTo: 'projects';
                  value: string | Project;
                }
              | {
                  relationTo: 'services';
                  value: string | Service;
                };
            label: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  title: string;
  image?: (string | null) | Media;
  description: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  items: {
    title: string;
    description: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    image: string | Media;
    id?: string | null;
  }[];
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  pageBlocks?: (SectionBlockProps | CTABlockProps)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  slug: string;
  slugLock?: boolean | null;
  url?: string | null;
  collectionTitle?: string | null;
  thumbnail?: (string | null) | Media;
  categories: (string | Category)[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlockProps".
 */
export interface CTABlockProps {
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  link: {
    type: 'reference' | 'custom';
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'projects';
          value: string | Project;
        } | null)
      | ({
          relationTo: 'services';
          value: string | Service;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'categories';
          value: string | Category;
        } | null);
    url?: string | null;
    label: string;
    variant?: ('fill' | 'outlined') | null;
    color?: ('primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet') | null;
    hoverColor?:
      | ('default' | 'primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet')
      | null;
    buttonShadow?: ('none' | 'small' | 'medium' | 'large') | null;
    className?: string | null;
  };
  blockVariant?: ('fill' | 'outlined' | 'outlined-thick') | null;
  backgroundColour?:
    | (
        | 'none'
        | 'primary'
        | 'secondary'
        | 'accent'
        | 'gradient-light'
        | 'gradient-primary'
        | 'gradient-secondary'
        | 'gradient-accent'
        | 'gradient-grey'
      )
    | null;
  borderRadius?: ('none' | 'small' | 'medium' | 'large' | 'circle') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  slug: string;
  slugLock?: boolean | null;
  url?: string | null;
  thumbnail?: (string | null) | Media;
  categories: (string | Category)[];
  /**
   * A short description of the post, used for previews and listings.
   */
  excerpt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  description?: string | null;
  heroContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The breadcrumbs for the category. These breadcrumbs will appear at the top of the page.
   */
  breadcrumb?: {
    breadcrumbContainer?: ('none' | 'boxed' | 'outlined') | null;
    breadcrumbBackground?: ('none' | 'light' | 'dark' | 'translucent') | null;
    breadcrumbOutlineColor?:
      | ('secondary' | 'accent' | 'urban-steel' | 'slate' | 'light-grey')
      | null;
    breadcrumbs?:
      | {
          relationTo:
            | {
                relationTo: 'pages';
                value: string | Page;
              }
            | {
                relationTo: 'categories';
                value: string | Category;
              };
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  layout?: ArchiveBlockProps[] | null;
  /**
   * The content to display in the CTA.
   */
  ctaContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The link to display in the CTA.
   */
  ctaLink: {
    type: 'reference' | 'custom';
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'projects';
          value: string | Project;
        } | null)
      | ({
          relationTo: 'services';
          value: string | Service;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'categories';
          value: string | Category;
        } | null);
    url?: string | null;
    label: string;
    variant?: ('fill' | 'outlined') | null;
    color?: ('primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet') | null;
    hoverColor?:
      | ('default' | 'primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet')
      | null;
    buttonShadow?: ('none' | 'small' | 'medium' | 'large') | null;
    className?: string | null;
  };
  /**
   * Customize the appearance of the CTA.
   */
  ctaAppearance?: {
    blockVariant?: ('fill' | 'outlined' | 'outlined-thick') | null;
    backgroundColour?:
      | (
          | 'none'
          | 'primary'
          | 'secondary'
          | 'accent'
          | 'gradient-light'
          | 'gradient-primary'
          | 'gradient-secondary'
          | 'gradient-accent'
          | 'gradient-grey'
        )
      | null;
    borderRadius?: ('none' | 'small' | 'medium' | 'large' | 'circle') | null;
  };
  slug: string;
  slugLock?: boolean | null;
  parentCategory?: (string | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlockProps".
 */
export interface ArchiveBlockProps {
  data: 'projects' | 'posts' | 'categories';
  categoriesToArchive?: (string | Category)[] | null;
  showFilter: boolean;
  filterShowAllButton?: boolean | null;
  viewType: 'list' | 'grid';
  numberOfProjects: number;
  /**
   * Grid appearance options for the block, this will only affect desktop screens as mobile is a standard flex one column layout.
   */
  gridAppearance?: {
    blockSize?:
      | (
          | 'col-span-1'
          | 'col-span-2'
          | 'col-span-3'
          | 'col-span-4'
          | 'col-span-5'
          | 'col-span-6'
          | 'col-span-7'
          | 'col-span-8'
          | 'col-span-9'
          | 'col-span-10'
          | 'col-span-11'
          | 'col-span-12'
          | 'col-span-13'
          | 'col-span-14'
          | 'col-span-15'
          | 'col-span-16'
        )
      | null;
    alignSelf?: ('stretch' | 'start' | 'center' | 'end') | null;
    justifySelf?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'archiveBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinksGroupBlockProps".
 */
export interface LinksGroupBlockProps {
  linksGroup?:
    | {
        link: {
          type: 'reference' | 'custom';
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'projects';
                value: string | Project;
              } | null)
            | ({
                relationTo: 'services';
                value: string | Service;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'categories';
                value: string | Category;
              } | null);
          url?: string | null;
          label: string;
          variant?: ('fill' | 'outlined') | null;
          color?: ('primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet') | null;
          hoverColor?:
            | ('default' | 'primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet')
            | null;
          buttonShadow?: ('none' | 'small' | 'medium' | 'large') | null;
          className?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Grid appearance options for the block, this will only affect desktop screens as mobile is a standard flex one column layout.
   */
  gridAppearance?: {
    blockSize?:
      | (
          | 'col-span-1'
          | 'col-span-2'
          | 'col-span-3'
          | 'col-span-4'
          | 'col-span-5'
          | 'col-span-6'
          | 'col-span-7'
          | 'col-span-8'
          | 'col-span-9'
          | 'col-span-10'
          | 'col-span-11'
          | 'col-span-12'
          | 'col-span-13'
          | 'col-span-14'
          | 'col-span-15'
          | 'col-span-16'
        )
      | null;
    alignSelf?: ('stretch' | 'start' | 'center' | 'end') | null;
    justifySelf?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'links-group';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroBlockProps".
 */
export interface IntroBlockProps {
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  textAlign?: ('left' | 'center' | 'right') | null;
  blockName?: string | null;
  /**
   * Grid appearance options for the block, this will only affect desktop screens as mobile is a standard flex one column layout.
   */
  gridAppearance?: {
    blockSize?:
      | (
          | 'col-span-1'
          | 'col-span-2'
          | 'col-span-3'
          | 'col-span-4'
          | 'col-span-5'
          | 'col-span-6'
          | 'col-span-7'
          | 'col-span-8'
          | 'col-span-9'
          | 'col-span-10'
          | 'col-span-11'
          | 'col-span-12'
          | 'col-span-13'
          | 'col-span-14'
          | 'col-span-15'
          | 'col-span-16'
        )
      | null;
    alignSelf?: ('stretch' | 'start' | 'center' | 'end') | null;
    justifySelf?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  id?: string | null;
  blockType: 'introBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlockProps".
 */
export interface MediaBlockProps {
  mediaType: 'image' | 'video' | 'pdf';
  media: string | Media;
  showCaption?: boolean | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  borderRadius?: ('none' | 'small' | 'medium' | 'large' | 'circle') | null;
  borderRadiusSides?: ('top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'all')[] | null;
  videoPlayerWidth?: ('100%' | '50%' | '33%' | '25%') | null;
  videoWidth?: number | null;
  videoHeight?: number | null;
  pdfWidth?: string | null;
  pdfHeight?: string | null;
  /**
   * Grid appearance options for the block, this will only affect desktop screens as mobile is a standard flex one column layout.
   */
  gridAppearance?: {
    blockSize?:
      | (
          | 'col-span-1'
          | 'col-span-2'
          | 'col-span-3'
          | 'col-span-4'
          | 'col-span-5'
          | 'col-span-6'
          | 'col-span-7'
          | 'col-span-8'
          | 'col-span-9'
          | 'col-span-10'
          | 'col-span-11'
          | 'col-span-12'
          | 'col-span-13'
          | 'col-span-14'
          | 'col-span-15'
          | 'col-span-16'
        )
      | null;
    alignSelf?: ('stretch' | 'start' | 'center' | 'end') | null;
    justifySelf?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  className?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardBlockProps".
 */
export interface CardBlockProps {
  relationTo: 'default' | 'projects' | 'services' | 'posts';
  relatedProject?: (string | null) | Project;
  relatedService?: (string | null) | Service;
  relatedPost?: (string | null) | Post;
  /**
   * The title of the card.
   */
  title?: string | null;
  /**
   * Whether to use an inner container for the card content.
   */
  insideContainer?: ('yes' | 'no') | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * (Leave blank if you want to use the project type set in the project itself)
   */
  projectType?: string | null;
  /**
   * (Leave blank if you want to use the service description set in the service itself)
   */
  serviceContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Use this to override the default post excerpt
   */
  postContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cardImage?: {
    image?: (string | null) | Media;
    /**
     * Position the image inside or outside the card content.
     */
    imagePosition?: ('inside' | 'outside') | null;
    /**
     * Align the image at the top or bottom of the card content.
     */
    imageAlign?: ('top' | 'bottom') | null;
    /**
     * The border radius of the image.
     */
    imageBorderRadius?: ('none' | 'top' | 'bottom' | 'left' | 'right' | 'all') | null;
  };
  className?: string | null;
  textAlign?: ('left' | 'centered' | 'right') | null;
  /**
   * Grid appearance options for the block, this will only affect desktop screens as mobile is a standard flex one column layout.
   */
  gridAppearance?: {
    blockSize?:
      | (
          | 'col-span-1'
          | 'col-span-2'
          | 'col-span-3'
          | 'col-span-4'
          | 'col-span-5'
          | 'col-span-6'
          | 'col-span-7'
          | 'col-span-8'
          | 'col-span-9'
          | 'col-span-10'
          | 'col-span-11'
          | 'col-span-12'
          | 'col-span-13'
          | 'col-span-14'
          | 'col-span-15'
          | 'col-span-16'
        )
      | null;
    alignSelf?: ('stretch' | 'start' | 'center' | 'end') | null;
    justifySelf?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlockProps".
 */
export interface AccordionBlockProps {
  accordionContent?:
    | {
        title: string;
        content: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  container?: ('card' | 'none') | null;
  indexCounter?: ('true' | 'false') | null;
  /**
   * Grid appearance options for the block, this will only affect desktop screens as mobile is a standard flex one column layout.
   */
  gridAppearance?: {
    blockSize?:
      | (
          | 'col-span-1'
          | 'col-span-2'
          | 'col-span-3'
          | 'col-span-4'
          | 'col-span-5'
          | 'col-span-6'
          | 'col-span-7'
          | 'col-span-8'
          | 'col-span-9'
          | 'col-span-10'
          | 'col-span-11'
          | 'col-span-12'
          | 'col-span-13'
          | 'col-span-14'
          | 'col-span-15'
          | 'col-span-16'
        )
      | null;
    alignSelf?: ('stretch' | 'start' | 'center' | 'end') | null;
    justifySelf?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordionBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlockProps".
 */
export interface CarouselBlockProps {
  carouselItems?: (CardBlockProps | MediaBlockProps)[] | null;
  carouselConfig: {
    autoHeight: boolean;
    autoPlay: boolean;
    keyboardControls: boolean;
    buttonNavigation: boolean;
    pagination: boolean;
    loop: boolean;
    direction: 'horizontal' | 'vertical';
    focus?: boolean | null;
    paginationType?: ('bullets' | 'progress') | null;
    /**
     * The spacing between slides in pixels.
     */
    slideSpacing: number;
    /**
     * The number of slides to show at a time.
     */
    slidesPerView: number;
    /**
     * The number of slides to scroll at a time.
     */
    slidesToScroll: 'auto' | '1' | '2' | '3' | '4';
  };
  /**
   * You can change the class names for the carousel. This is especially useful if you are using a CSS framework like Tailwind or BEM naming conventions. It is also helpful if you want to easily style the carousel disabled state with CSS.
   */
  carouselClassNames?: {
    container?: string | null;
    wrapper?: string | null;
    slide?: string | null;
  };
  /**
   * Grid appearance options for the block, this will only affect desktop screens as mobile is a standard flex one column layout.
   */
  gridAppearance?: {
    blockSize?:
      | (
          | 'col-span-1'
          | 'col-span-2'
          | 'col-span-3'
          | 'col-span-4'
          | 'col-span-5'
          | 'col-span-6'
          | 'col-span-7'
          | 'col-span-8'
          | 'col-span-9'
          | 'col-span-10'
          | 'col-span-11'
          | 'col-span-12'
          | 'col-span-13'
          | 'col-span-14'
          | 'col-span-15'
          | 'col-span-16'
        )
      | null;
    alignSelf?: ('stretch' | 'start' | 'center' | 'end') | null;
    justifySelf?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  /**
   * Enable responsive mode to disable the carousel at  a certain breakpoint. This is useful if you want to use the carousel on smaller screens but still want to have the ability to navigate through the slides.
   */
  responsive?: boolean | null;
  breakpointSelection?: string | null;
  /**
   * What it the size of the grid?
   */
  gridColumns: '1' | '2' | '3' | '4' | '6' | '8' | '12';
  /**
   * How many colummns should the slides span?
   */
  slideColumnSpan: '1' | '2' | '3' | '4' | '6' | '12';
  /**
   * The amount of featured items, these will appear larger compared to the rest of the items.
   */
  featuredItems?: ('0' | '1' | '2') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carouselBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BioBlockProps".
 */
export interface BioBlockProps {
  items?:
    | {
        label?: ('location' | 'education' | 'email') | null;
        value?: string | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'projects';
                value: string | Project;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Grid appearance options for the block, this will only affect desktop screens as mobile is a standard flex one column layout.
   */
  gridAppearance?: {
    blockSize?:
      | (
          | 'col-span-1'
          | 'col-span-2'
          | 'col-span-3'
          | 'col-span-4'
          | 'col-span-5'
          | 'col-span-6'
          | 'col-span-7'
          | 'col-span-8'
          | 'col-span-9'
          | 'col-span-10'
          | 'col-span-11'
          | 'col-span-12'
          | 'col-span-13'
          | 'col-span-14'
          | 'col-span-15'
          | 'col-span-16'
        )
      | null;
    alignSelf?: ('stretch' | 'start' | 'center' | 'end') | null;
    justifySelf?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'bioBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ToolsBlockProps".
 */
export interface ToolsBlockProps {
  /**
   * Create a list of tools that you use, featuring their icon, title and link.
   */
  tools?:
    | {
        icon: string | Media;
        name: string;
        description?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        link: {
          type: 'reference' | 'custom';
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'projects';
                value: string | Project;
              } | null)
            | ({
                relationTo: 'services';
                value: string | Service;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'categories';
                value: string | Category;
              } | null);
          url?: string | null;
          label: string;
          variant?: ('fill' | 'outlined') | null;
          color?: ('primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet') | null;
          hoverColor?:
            | ('default' | 'primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet')
            | null;
          buttonShadow?: ('none' | 'small' | 'medium' | 'large') | null;
          className?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Grid appearance options for the block, this will only affect desktop screens as mobile is a standard flex one column layout.
   */
  gridAppearance?: {
    blockSize?:
      | (
          | 'col-span-1'
          | 'col-span-2'
          | 'col-span-3'
          | 'col-span-4'
          | 'col-span-5'
          | 'col-span-6'
          | 'col-span-7'
          | 'col-span-8'
          | 'col-span-9'
          | 'col-span-10'
          | 'col-span-11'
          | 'col-span-12'
          | 'col-span-13'
          | 'col-span-14'
          | 'col-span-15'
          | 'col-span-16'
        )
      | null;
    alignSelf?: ('stretch' | 'start' | 'center' | 'end') | null;
    justifySelf?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'toolsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TopTracksBlockProps".
 */
export interface TopTracksBlockProps {
  type?: ('carousel' | 'list') | null;
  numberOfTracks: number;
  container: 'none' | 'card';
  loop?: ('loop' | 'noloop') | null;
  slideSpacing: number;
  focus?: ('focused' | 'unfocused') | null;
  /**
   * Grid appearance options for the block, this will only affect desktop screens as mobile is a standard flex one column layout.
   */
  gridAppearance?: {
    blockSize?:
      | (
          | 'col-span-1'
          | 'col-span-2'
          | 'col-span-3'
          | 'col-span-4'
          | 'col-span-5'
          | 'col-span-6'
          | 'col-span-7'
          | 'col-span-8'
          | 'col-span-9'
          | 'col-span-10'
          | 'col-span-11'
          | 'col-span-12'
          | 'col-span-13'
          | 'col-span-14'
          | 'col-span-15'
          | 'col-span-16'
        )
      | null;
    alignSelf?: ('stretch' | 'start' | 'center' | 'end') | null;
    justifySelf?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'topTracksBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedProjectsBlockProps".
 */
export interface RelatedProjectsBlockProps {
  relatedCollection: 'projects' | 'posts';
  relatedCategory: 'branding' | 'digital' | 'marketing' | 'print' | 'graphic-design';
  numberOfRelatedItems: number;
  /**
   * Grid appearance options for the block, this will only affect desktop screens as mobile is a standard flex one column layout.
   */
  gridAppearance?: {
    blockSize?:
      | (
          | 'col-span-1'
          | 'col-span-2'
          | 'col-span-3'
          | 'col-span-4'
          | 'col-span-5'
          | 'col-span-6'
          | 'col-span-7'
          | 'col-span-8'
          | 'col-span-9'
          | 'col-span-10'
          | 'col-span-11'
          | 'col-span-12'
          | 'col-span-13'
          | 'col-span-14'
          | 'col-span-15'
          | 'col-span-16'
        )
      | null;
    alignSelf?: ('stretch' | 'start' | 'center' | 'end') | null;
    justifySelf?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'relatedProjectsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionGroupBlockProps".
 */
export interface SectionGroupBlockProps {
  sectionBlocks?: (SectionBlockProps | DividerBlockProps)[] | null;
  appearance?: {
    /**
     * The layout of the section, you can choose between a blocks layout, boxed content, or full-width blocks layout.
     */
    sectionType?: ('default' | 'full-width' | 'boxed') | null;
    backgroundColour?:
      | (
          | 'none'
          | 'primary'
          | 'secondary'
          | 'accent'
          | 'gradient-light'
          | 'gradient-primary'
          | 'gradient-secondary'
          | 'gradient-accent'
          | 'gradient-grey'
        )
      | null;
  };
  blockName?: string | null;
  hiddenSlug?: string | null;
  id?: string | null;
  blockType: 'sectionGroup';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabbedContentBlockProps".
 */
export interface TabbedContentBlockProps {
  contentType?: ('custom' | 'services') | null;
  content?:
    | {
        title?: string | null;
        description?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        addLink?: boolean | null;
        link?: {
          type: 'reference' | 'custom';
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'projects';
                value: string | Project;
              } | null)
            | ({
                relationTo: 'services';
                value: string | Service;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'categories';
                value: string | Category;
              } | null);
          url?: string | null;
          label: string;
          variant?: ('fill' | 'outlined') | null;
          color?: ('primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet') | null;
          hoverColor?:
            | ('default' | 'primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet')
            | null;
          buttonShadow?: ('none' | 'small' | 'medium' | 'large') | null;
          className?: string | null;
        };
        items?:
          | {
              title?: string | null;
              description?: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              image?: (string | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Grid appearance options for the block, this will only affect desktop screens as mobile is a standard flex one column layout.
   */
  gridAppearance?: {
    blockSize?:
      | (
          | 'col-span-1'
          | 'col-span-2'
          | 'col-span-3'
          | 'col-span-4'
          | 'col-span-5'
          | 'col-span-6'
          | 'col-span-7'
          | 'col-span-8'
          | 'col-span-9'
          | 'col-span-10'
          | 'col-span-11'
          | 'col-span-12'
          | 'col-span-13'
          | 'col-span-14'
          | 'col-span-15'
          | 'col-span-16'
        )
      | null;
    alignSelf?: ('stretch' | 'start' | 'center' | 'end') | null;
    justifySelf?: ('start' | 'center' | 'end' | 'stretch') | null;
  };
  className?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tabbedContentBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'projects';
          value: string | Project;
        } | null)
      | ({
          relationTo: 'services';
          value: string | Service;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: string | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?: T | HeroBlockPropsSelect<T>;
  layout?:
    | T
    | {
        divider?: T | DividerBlockPropsSelect<T>;
        section?: T | SectionBlockPropsSelect<T>;
        sectionGroup?: T | SectionGroupBlockPropsSelect<T>;
        archiveBlock?: T | ArchiveBlockPropsSelect<T>;
        tabbedContentBlock?: T | TabbedContentBlockPropsSelect<T>;
        ctaBlock?: T | CTABlockPropsSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  slugLock?: T;
  url?: T;
  thumbnail?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlockProps_select".
 */
export interface HeroBlockPropsSelect<T extends boolean = true> {
  richText?: T;
  heroStyle?: T;
  type?: T;
  blurredBackground?: T;
  image?: T;
  showBreadcrumb?: T;
  breadcrumbContainer?: T;
  breadcrumbBackground?: T;
  breadcrumbs?:
    | T
    | {
        relationTo?: T;
        label?: T;
        id?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DividerBlockProps_select".
 */
export interface DividerBlockPropsSelect<T extends boolean = true> {
  type?: T;
  weight?: T;
  width?: T;
  centered?: T;
  color?: T;
  opacity?: T;
  className?: T;
  gridAppearance?:
    | T
    | {
        blockSize?: T;
        alignSelf?: T;
        justifySelf?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionBlockProps_select".
 */
export interface SectionBlockPropsSelect<T extends boolean = true> {
  sectionBlocks?:
    | T
    | {
        divider?: T | DividerBlockPropsSelect<T>;
        links?: T | LinksBlockPropsSelect<T>;
        'links-group'?: T | LinksGroupBlockPropsSelect<T>;
        introBlock?: T | IntroBlockPropsSelect<T>;
        mediaBlock?: T | MediaBlockPropsSelect<T>;
        cardBlock?: T | CardBlockPropsSelect<T>;
        accordionBlock?: T | AccordionBlockPropsSelect<T>;
        carouselBlock?: T | CarouselBlockPropsSelect<T>;
        bioBlock?: T | BioBlockPropsSelect<T>;
        toolsBlock?: T | ToolsBlockPropsSelect<T>;
        topTracksBlock?: T | TopTracksBlockPropsSelect<T>;
        relatedProjectsBlock?: T | RelatedProjectsBlockPropsSelect<T>;
      };
  boxedContent?: T;
  appearance?:
    | T
    | {
        sectionType?: T;
        alignContent?: T;
        backgroundColour?: T;
        borderRadius?: T;
      };
  blockName?: T;
  hiddenSlug?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinksBlockProps_select".
 */
export interface LinksBlockPropsSelect<T extends boolean = true> {
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        variant?: T;
        color?: T;
        hoverColor?: T;
        buttonShadow?: T;
        className?: T;
      };
  gridAppearance?:
    | T
    | {
        blockSize?: T;
        alignSelf?: T;
        justifySelf?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinksGroupBlockProps_select".
 */
export interface LinksGroupBlockPropsSelect<T extends boolean = true> {
  linksGroup?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              variant?: T;
              color?: T;
              hoverColor?: T;
              buttonShadow?: T;
              className?: T;
            };
        id?: T;
      };
  gridAppearance?:
    | T
    | {
        blockSize?: T;
        alignSelf?: T;
        justifySelf?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroBlockProps_select".
 */
export interface IntroBlockPropsSelect<T extends boolean = true> {
  introContent?: T;
  textAlign?: T;
  blockName?: T;
  gridAppearance?:
    | T
    | {
        blockSize?: T;
        alignSelf?: T;
        justifySelf?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlockProps_select".
 */
export interface MediaBlockPropsSelect<T extends boolean = true> {
  mediaType?: T;
  media?: T;
  showCaption?: T;
  caption?: T;
  borderRadius?: T;
  borderRadiusSides?: T;
  videoPlayerWidth?: T;
  videoWidth?: T;
  videoHeight?: T;
  pdfWidth?: T;
  pdfHeight?: T;
  gridAppearance?:
    | T
    | {
        blockSize?: T;
        alignSelf?: T;
        justifySelf?: T;
      };
  className?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardBlockProps_select".
 */
export interface CardBlockPropsSelect<T extends boolean = true> {
  relationTo?: T;
  relatedProject?: T;
  relatedService?: T;
  relatedPost?: T;
  title?: T;
  insideContainer?: T;
  content?: T;
  projectType?: T;
  serviceContent?: T;
  postContent?: T;
  cardImage?:
    | T
    | {
        image?: T;
        imagePosition?: T;
        imageAlign?: T;
        imageBorderRadius?: T;
      };
  className?: T;
  textAlign?: T;
  gridAppearance?:
    | T
    | {
        blockSize?: T;
        alignSelf?: T;
        justifySelf?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlockProps_select".
 */
export interface AccordionBlockPropsSelect<T extends boolean = true> {
  accordionContent?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  container?: T;
  indexCounter?: T;
  gridAppearance?:
    | T
    | {
        blockSize?: T;
        alignSelf?: T;
        justifySelf?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlockProps_select".
 */
export interface CarouselBlockPropsSelect<T extends boolean = true> {
  carouselItems?:
    | T
    | {
        cardBlock?: T | CardBlockPropsSelect<T>;
        mediaBlock?: T | MediaBlockPropsSelect<T>;
      };
  carouselConfig?:
    | T
    | {
        autoHeight?: T;
        autoPlay?: T;
        keyboardControls?: T;
        buttonNavigation?: T;
        pagination?: T;
        loop?: T;
        direction?: T;
        focus?: T;
        paginationType?: T;
        slideSpacing?: T;
        slidesPerView?: T;
        slidesToScroll?: T;
      };
  carouselClassNames?:
    | T
    | {
        container?: T;
        wrapper?: T;
        slide?: T;
      };
  gridAppearance?:
    | T
    | {
        blockSize?: T;
        alignSelf?: T;
        justifySelf?: T;
      };
  responsive?: T;
  breakpointSelection?: T;
  gridColumns?: T;
  slideColumnSpan?: T;
  featuredItems?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BioBlockProps_select".
 */
export interface BioBlockPropsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        value?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  gridAppearance?:
    | T
    | {
        blockSize?: T;
        alignSelf?: T;
        justifySelf?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ToolsBlockProps_select".
 */
export interface ToolsBlockPropsSelect<T extends boolean = true> {
  tools?:
    | T
    | {
        icon?: T;
        name?: T;
        description?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              variant?: T;
              color?: T;
              hoverColor?: T;
              buttonShadow?: T;
              className?: T;
            };
        id?: T;
      };
  gridAppearance?:
    | T
    | {
        blockSize?: T;
        alignSelf?: T;
        justifySelf?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TopTracksBlockProps_select".
 */
export interface TopTracksBlockPropsSelect<T extends boolean = true> {
  type?: T;
  numberOfTracks?: T;
  container?: T;
  loop?: T;
  slideSpacing?: T;
  focus?: T;
  gridAppearance?:
    | T
    | {
        blockSize?: T;
        alignSelf?: T;
        justifySelf?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedProjectsBlockProps_select".
 */
export interface RelatedProjectsBlockPropsSelect<T extends boolean = true> {
  relatedCollection?: T;
  relatedCategory?: T;
  numberOfRelatedItems?: T;
  gridAppearance?:
    | T
    | {
        blockSize?: T;
        alignSelf?: T;
        justifySelf?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionGroupBlockProps_select".
 */
export interface SectionGroupBlockPropsSelect<T extends boolean = true> {
  sectionBlocks?:
    | T
    | {
        section?: T | SectionBlockPropsSelect<T>;
        divider?: T | DividerBlockPropsSelect<T>;
      };
  appearance?:
    | T
    | {
        sectionType?: T;
        backgroundColour?: T;
      };
  blockName?: T;
  hiddenSlug?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlockProps_select".
 */
export interface ArchiveBlockPropsSelect<T extends boolean = true> {
  data?: T;
  categoriesToArchive?: T;
  showFilter?: T;
  filterShowAllButton?: T;
  viewType?: T;
  numberOfProjects?: T;
  gridAppearance?:
    | T
    | {
        blockSize?: T;
        alignSelf?: T;
        justifySelf?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabbedContentBlockProps_select".
 */
export interface TabbedContentBlockPropsSelect<T extends boolean = true> {
  contentType?: T;
  content?:
    | T
    | {
        title?: T;
        description?: T;
        addLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              variant?: T;
              color?: T;
              hoverColor?: T;
              buttonShadow?: T;
              className?: T;
            };
        items?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              id?: T;
            };
        id?: T;
      };
  gridAppearance?:
    | T
    | {
        blockSize?: T;
        alignSelf?: T;
        justifySelf?: T;
      };
  className?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlockProps_select".
 */
export interface CTABlockPropsSelect<T extends boolean = true> {
  content?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        variant?: T;
        color?: T;
        hoverColor?: T;
        buttonShadow?: T;
        className?: T;
      };
  blockVariant?: T;
  backgroundColour?: T;
  borderRadius?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  heroContent?: T;
  breadcrumb?:
    | T
    | {
        breadcrumbContainer?: T;
        breadcrumbBackground?: T;
        breadcrumbOutlineColor?: T;
        breadcrumbs?:
          | T
          | {
              relationTo?: T;
              label?: T;
              id?: T;
            };
      };
  layout?:
    | T
    | {
        archiveBlock?: T | ArchiveBlockPropsSelect<T>;
      };
  ctaContent?: T;
  ctaLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        variant?: T;
        color?: T;
        hoverColor?: T;
        buttonShadow?: T;
        className?: T;
      };
  ctaAppearance?:
    | T
    | {
        blockVariant?: T;
        backgroundColour?: T;
        borderRadius?: T;
      };
  slug?: T;
  slugLock?: T;
  parentCategory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        titleOverride?: T;
        'clonedLock-110371416'?: T;
        typeOverride?: T;
        'clonedLock-1380773734'?: T;
        backgroundImage?: T;
        blurredBackground?: T;
        breadcrumbs?:
          | T
          | {
              showBreadcrumb?: T;
              breadcrumbContainer?: T;
              breadcrumbBackground?: T;
              breadcrumbs?:
                | T
                | {
                    relationTo?: T;
                    label?: T;
                    id?: T;
                  };
            };
      };
  details?:
    | T
    | {
        date?: T;
        type?: T;
        tools?: T;
        name?: T;
        url?: T;
        previewLabel?: T;
        previewUrl?: T;
        description?: T;
      };
  gallery?:
    | T
    | {
        media?: T;
        showCaption?: T;
        caption?: T;
        id?: T;
      };
  galleryOptions?:
    | T
    | {
        autoHeight?: T;
        autoPlay?: T;
        keyboardControls?: T;
        buttonNavigation?: T;
        pagination?: T;
        loop?: T;
        direction?: T;
        focus?: T;
        paginationType?: T;
        paginationColor?: T;
        slideSpacing?: T;
        slidesPerView?: T;
        slidesToScroll?: T;
      };
  content?: T;
  ctaContent?: T;
  ctaLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        variant?: T;
        color?: T;
        hoverColor?: T;
        buttonShadow?: T;
        className?: T;
      };
  ctaAppearance?:
    | T
    | {
        blockVariant?: T;
        backgroundColour?: T;
        borderRadius?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  slugLock?: T;
  url?: T;
  thumbnail?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        typeOverride?: T;
        'clonedLock-1050015322'?: T;
        titleOverride?: T;
        'clonedLock-110371416'?: T;
        backgroundImage?: T;
        blurredBackground?: T;
        breadcrumbs?:
          | T
          | {
              showBreadcrumb?: T;
              breadcrumbContainer?: T;
              breadcrumbBackground?: T;
              breadcrumbs?:
                | T
                | {
                    relationTo?: T;
                    label?: T;
                    id?: T;
                  };
            };
      };
  title?: T;
  image?: T;
  description?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  introContent?: T;
  pageBlocks?:
    | T
    | {
        section?: T | SectionBlockPropsSelect<T>;
        ctaBlock?: T | CTABlockPropsSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  slugLock?: T;
  url?: T;
  collectionTitle?: T;
  thumbnail?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  slugLock?: T;
  url?: T;
  thumbnail?: T;
  categories?: T;
  excerpt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breakpoints".
 */
export interface Breakpoint {
  id: string;
  breakpoints?:
    | {
        name: string;
        breakpoint: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social".
 */
export interface Social {
  id: string;
  'social-network'?:
    | {
        username: string;
        network: 'x' | 'instagram' | 'github' | 'linkedin' | 'youtube';
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems: {
    link: {
      type: 'reference' | 'custom';
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'projects';
            value: string | Project;
          } | null)
        | ({
            relationTo: 'services';
            value: string | Service;
          } | null)
        | ({
            relationTo: 'posts';
            value: string | Post;
          } | null)
        | ({
            relationTo: 'categories';
            value: string | Category;
          } | null);
      url?: string | null;
      label: string;
      variant?: ('fill' | 'outlined') | null;
      color?: ('primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet') | null;
      hoverColor?:
        | ('default' | 'primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet')
        | null;
      buttonShadow?: ('none' | 'small' | 'medium' | 'large') | null;
      className?: string | null;
    };
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems: {
    link: {
      type: 'reference' | 'custom';
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'projects';
            value: string | Project;
          } | null)
        | ({
            relationTo: 'services';
            value: string | Service;
          } | null)
        | ({
            relationTo: 'posts';
            value: string | Post;
          } | null)
        | ({
            relationTo: 'categories';
            value: string | Category;
          } | null);
      url?: string | null;
      label: string;
      variant?: ('fill' | 'outlined') | null;
      color?: ('primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet') | null;
      hoverColor?:
        | ('default' | 'primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet')
        | null;
      buttonShadow?: ('none' | 'small' | 'medium' | 'large') | null;
      className?: string | null;
    };
    id?: string | null;
  }[];
  logoColor:
    | 'primary'
    | 'secondary'
    | 'accent'
    | 'light'
    | 'slate'
    | 'frosted-sage'
    | 'urban-steel';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breakpoints_select".
 */
export interface BreakpointsSelect<T extends boolean = true> {
  breakpoints?:
    | T
    | {
        name?: T;
        breakpoint?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social_select".
 */
export interface SocialSelect<T extends boolean = true> {
  'social-network'?:
    | T
    | {
        username?: T;
        network?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              variant?: T;
              color?: T;
              hoverColor?: T;
              buttonShadow?: T;
              className?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              variant?: T;
              color?: T;
              hoverColor?: T;
              buttonShadow?: T;
              className?: T;
            };
        id?: T;
      };
  logoColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'projects';
          value: string | Project;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinksBlockRichtextProps".
 */
export interface LinksBlockRichtextProps {
  link: {
    type: 'reference' | 'custom';
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'projects';
          value: string | Project;
        } | null)
      | ({
          relationTo: 'services';
          value: string | Service;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'categories';
          value: string | Category;
        } | null);
    url?: string | null;
    label: string;
    variant?: ('fill' | 'outlined') | null;
    color?: ('primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet') | null;
    hoverColor?:
      | ('default' | 'primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet')
      | null;
    buttonShadow?: ('none' | 'small' | 'medium' | 'large') | null;
    className?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'links-richtext';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinksGroupRichtextProps".
 */
export interface LinksGroupRichtextProps {
  linksGroup?:
    | {
        link: {
          type: 'reference' | 'custom';
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'projects';
                value: string | Project;
              } | null)
            | ({
                relationTo: 'services';
                value: string | Service;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'categories';
                value: string | Category;
              } | null);
          url?: string | null;
          label: string;
          variant?: ('fill' | 'outlined') | null;
          color?: ('primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet') | null;
          hoverColor?:
            | ('default' | 'primary' | 'secondary' | 'accent' | 'sage' | 'slate' | 'bittersweet')
            | null;
          buttonShadow?: ('none' | 'small' | 'medium' | 'large') | null;
          className?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'links-group-richtext';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaRichtextBlockProps".
 */
export interface MediaRichtextBlockProps {
  mediaType: 'image' | 'video' | 'pdf';
  media: string | Media;
  showCaption?: boolean | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  borderRadius?: ('none' | 'small' | 'medium' | 'large' | 'circle') | null;
  borderRadiusSides?: ('top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'all')[] | null;
  videoPlayerWidth?: ('100%' | '50%' | '33%' | '25%') | null;
  videoWidth?: number | null;
  videoHeight?: number | null;
  pdfWidth?: string | null;
  pdfHeight?: string | null;
  className?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaRichtextBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
